//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCashTransaction
    {
        public long CashID { get; set; }
        public string StandardAccount { get; set; }
        public string AccountName { get; set; }
        public string BankBalance { get; set; }
        public string LiquidFundMV { get; set; }
        public string Payable { get; set; }
        public string Receivable { get; set; }
        public string PendingOrdersCash { get; set; }
        public string AvailableCashandEq { get; set; }
        public string MarketValue { get; set; }
        public string CashEqasofMV { get; set; }
        public string ModelName { get; set; }
        public string ClientStatus { get; set; }
        public string InceptionDate { get; set; }
        public string SchemeName { get; set; }
        public string Constraints { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
