//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstCOA
    {
        public int ACID { get; set; }
        public Nullable<int> BankCustID { get; set; }
        public string AccountCode { get; set; }
        public string Accountname { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
