//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTBTransaction
    {
        public long TransLineid { get; set; }
        public string AccountId { get; set; }
        public string AccountSubId { get; set; }
        public string AccountSubcat { get; set; }
        public string OpeningbalDR { get; set; }
        public string OpeningbalCR { get; set; }
        public string TransDuringperiodDR { get; set; }
        public string TransDuringperiodCR { get; set; }
        public string ClosingbalDR { get; set; }
        public string ClosingbalCR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
