//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrialbalanceTra
    {
        public long TBID { get; set; }
        public string BankCutomerAccountNo { get; set; }
        public string Accountno { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> OpeningbalDr { get; set; }
        public Nullable<decimal> OpeningbalCr { get; set; }
        public Nullable<decimal> TransPDr { get; set; }
        public Nullable<decimal> TransPCr { get; set; }
        public Nullable<decimal> CloseBalDr { get; set; }
        public Nullable<decimal> CloseBalCr { get; set; }
        public Nullable<System.DateTime> OpeningFrom { get; set; }
        public Nullable<System.DateTime> OpeningTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
